# Generated by Django 4.0.4 on 2022-06-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='people_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='number_of_patient',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='people_id_number',
        ),
        migrations.AddField(
            model_name='bio',
            name='about',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='bio',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Doctor_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Hospital_region',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='number_of_patients',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='address',
            name='home_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalcode',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bio',
            name='origin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='people',
            name='nickname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
