# Generated by Django 4.0.4 on 2022-06-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_remove_bio_people_id_remove_doctor_number_of_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='state.people'),
        ),
        migrations.AddField(
            model_name='bio',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='state.people'),
        ),
        migrations.AddField(
            model_name='people',
            name='patients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='state.doctor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='people',
            name='nickname',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
    ]
